// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lexfsegfzpottksiwgxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxleGZzZWdmenBvdHRrc2l3Z3hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTM0MjksImV4cCI6MjA1ODg4OTQyOX0.yzCnTgXhHLEQLs0bCv_ttDb8TYawiTjDC21IZVWs2Hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);