// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmwyvmrcokieicvoxrpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhtd3l2bXJjb2tpZWljdm94cnBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODgwOTUsImV4cCI6MjA2NDM2NDA5NX0.z8tFBChSkKOPv3kPJW66O0AdwBWFm9h_NH0-jaPojO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);