// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iahrquzemjxcchshdgxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhaHJxdXplbWp4Y2Noc2hkZ3hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTc5OTksImV4cCI6MjA2NDM3Mzk5OX0.rpl82BMll6zL-EeV7ofrHC8sofpZXl-b456BnzIuTKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);